name: mkdocs-dev 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  mkdocs-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          python -m pip install --upgrade pip
          pip install hatch mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocstrings-python mike
      - name: Fetch gh-pages
        run: |
          git fetch origin gh-pages --depth=1
          git status
      - uses: actions/checkout@v4 
      - run: |
          git config user.name github-actions  # https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token
          git config user.email github-actions@github.com
      - name: Deploy development version
        run: |
          mike list
          export VERSION=`hatch version`
          mike deploy "$VERSION+dev"
      - name: Add CNAME
        run: |
          git checkout gh-pages
          rm -rf CNAME && echo "flicker.perfectlyrandom.org" >> CNAME
          (git status --porcelain | grep -q .) && git add CNAME && git commit -m "Adding CNAME (by GitHub Actions)"
          git status
      - name: Push to gh-pages
        run: git push
