name: PyPI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (must be an existing tag)'
        required: true
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref_name }}  # Use the manually entered tag or the release tag

      - name: Verify tag
        run: |
          TAG=${{ github.event.inputs.tag || github.ref_name }}
          if ! git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Error: Tag $TAG does not exist in the repository."
            exit 1
          fi
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}-python-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch twine

      - name: Build package
        run: |
          hatch clean
          hatch build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to Prod PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PROD_PYPI_PASSWORD }}
